### PR TITLE
Feature/channel capacity

### PR DESCRIPTION
**Pull request by AbiudSM**
Hi Brana :3 here is the channel capacity algorithm, check it to see if it is ok, otherwise I'll feel bad u_u

### CODE REVIEW

**Comment by AbiudSM** [comment]
I change the p array to the output requencies

**Comment by AbiudSM** [comment]
Add the program to get the output frequencies. 

The validations are commented because I don't know whether to add them or not, with floating numbers sometimes the sum is not 1

**Review by danielcont — APPROVED** [review]
tested the code.  looks like it works fine.  good job Robertudo!

**Review by danielcont — APPROVED** [review]
approved

**Pull request merged**
